version: "3.9"

services:
  api:
    build: .
    container_name: rag_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./documents:/app/documents
      - ./chroma_db:/app/chroma_db


  streamlit:
    build: .
    container_name: rag_streamlit
    command: streamlit run app/interface.py --server.port=8501 --server.headless=true
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    volumes:
      - .:/app
    depends_on:
      - api
